variables:
  GCP_SERVICE_ACCOUNT: $GCP_SERVICE_ACCOUNT
  GCP_WORKLOAD_IDENTITY_PROVIDER: $GCP_WORKLOAD_IDENTITY_PROVIDER
  GCP_SERVICE_ACCOUNT: $GCP_SERVICE_ACCOUNT

stages:
  - gcp-auth
  - automated-testing
  - integration
  - validation
  - pre-production
  - production

before_script:
  - rm -rf .terraform


v1-auth-0:
  stage: gcp-auth
  image: google/cloud-sdk:slim
  script:
    - echo $CI_JOB_JWT_V2 > .ci_job_jwt_file
    - cat .ci_job_jwt_file
    - echo "$GCP_WORKLOAD_IDENTITY_PROVIDER"
    - echo "$GCP_SERVICE_ACCOUNT"
    - gcloud iam workload-identity-pools create-cred-config "$GCP_WORKLOAD_IDENTITY_PROVIDER"
      --service-account="$GCP_SERVICE_ACCOUNT"
      --output-file=.gcp_temp_cred.json
      --credential-source-file=.ci_job_jwt_file
    - gcloud auth login --cred-file=`pwd`/.gcp_temp_cred.json
    - gcloud auth list

v1-auth-1:
  stage: gcp-auth
  needs: ["v1-auth-0"]
  image: dwdraju/alpine-curl-jq
  script: 
   ./gcp-sts.sh
  artifacts:
    reports:
      dotenv: CLOUDSDK_AUTH_ACCESS_TOKEN.env

v1-infra-core-automated-testing-step-0:
  stage: automated-testing
  needs:
    - job: "v1-auth-1"
      artifacts: true
  rules:
  - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "develop"'
    when: on_success
    changes:
      - demos/v1-self-managed/time-keeper-gcp/**/* 
  script:
    - echo "Running AUTOMATED TESTING Environment for Core Infra!"
    - echo "Cloud Access Token - ${CLOUDSDK_AUTH_ACCESS_TOKEN}"



v1-infra-core-automated-testing-step-1:
  stage: automated-testing
  needs: 
    - job: "v1-auth-1"
      artifacts: true
    - job: "v1-infra-core-automated-testing-step-0"
  rules:
  - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "develop"'
    when: on_success
    changes:
      - demos/v1-self-managed/time-keeper-gcp/**/* 
  image:
    name: hashicorp/terraform:light
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  script: 
    - export TF_WORKSPACE="at"
    - terraform --version
    - terraform -chdir="demos/v1-self-managed/time-keeper-gcp/" init
    - terraform -chdir="demos/v1-self-managed/time-keeper-gcp/" plan -var="env=at"
    
v1-infra-core-integration:
  stage: integration
  rules:
  - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "develop"'
    when: on_success
    changes:
      - demos/v1-self-managed/time-keeper-gcp/**/* 
  image:
    name: hashicorp/terraform:light
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  script: 
    - echo "Running INTEGRATION Environment for Core Infra!"
    - export TF_WORKSPACE="int"
    - terraform --version
    - terraform -chdir="demos/v1-self-managed/time-keeper-gcp/" init
    - terraform -chdir="demos/v1-self-managed/time-keeper-gcp/" plan -var="env=int"

v1-infra-core-validation:
  stage: validation
  rules:
  - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "develop"'
    when: on_success
    changes:
      - demos/v1-self-managed/time-keeper-gcp/**/* 
  image:
    name: hashicorp/terraform:light
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  script: 
    - echo "Running VALIDATION Environment for Core Infra!"
    - export TF_WORKSPACE="val"
    - terraform --version
    - terraform -chdir="demos/v1-self-managed/time-keeper-gcp/" init
    - terraform -chdir="demos/v1-self-managed/time-keeper-gcp/" plan -var="env=val"

v1-infra-core-pre-production:
  stage: pre-production
  when: manual
  rules:
  - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"'
    when: on_success
    changes:
      - demos/v1-self-managed/time-keeper-gcp/**/* 
  image:
    name: hashicorp/terraform:light
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  script: 
    - echo "Running PRE-PRODUCTION Environment for Core Infra!"
    - export TF_WORKSPACE="pp"
    - terraform --version
    - terraform -chdir="demos/v1-self-managed/time-keeper-gcp/" init
    - terraform -chdir="demos/v1-self-managed/time-keeper-gcp/" plan -var="env=pp"


v1-infra-core-production:
  stage: production
  when: manual
  rules:
  - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"'
    when: on_success
    changes:
      - demos/v1-self-managed/time-keeper-gcp/**/* 
  image:
    name: hashicorp/terraform:light
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  script: 
    - echo "Running PRODUCTION Environment for Core Infra!"
    - export TF_WORKSPACE="p"
    - terraform --version
    - terraform -chdir="demos/v1-self-managed/time-keeper-gcp/" init
    - terraform -chdir="demos/v1-self-managed/time-keeper-gcp/" plan -var="env=p"