gcp-auth:
  image: google/cloud-sdk:slim
  script:
    - echo ${CI_JOB_JWT_V2} > .ci_job_jwt_file
    - gcloud iam workload-identity-pools create-cred-config ${WORKLOAD_IDENTITY_PROVIDER}
      --service-account="${SERVICE_ACCOUNT_EMAIL}"
      --output-file=.gcp_temp_cred.json
      --credential-source-file=.ci_job_jwt_file
    - gcloud auth login --cred-file=`pwd`/.gcp_temp_cred.json
    - gcloud auth list

gcp-sts:
  image: dwdraju/alpine-curl-jq
  script: 
   ./run_gcp_sts.sh
  artifacts:
    reports:
      dotenv: GOOGLE_CLOUD_KEYFILE_JSON.env

gcp-playback:
  image: hashicorp/terraform:light
  needs:
    - job: gcp-sts
      artifacts: true
  script: 
   - echo "Hey... We Made it!"
   - echo "${CLOUDSDK_AUTH_ACCESS_TOKEN}"



