# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
#
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

stages:          # List of stages for jobs, and their order of execution
  - at
  - int
  - val
  - pp
  - p

v1-infra-core-at:
  stage: at
  rules:
  - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "env/at"'
    when: on_success
    changes:
      - demos/v1-self-managed/time-keeper-gcp/**/* 
  script: echo "Running AUTOMATION TESTING Environment for Core Infra!"
    

v1-infra-core-int:
  stage: int
  rules:
  - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "env/int"'
    when: on_success
    changes:
      - demos/v1-self-managed/time-keeper-gcp/**/* 
  script: echo "Running INTEGRATION Environment for Core Infra!"

v1-infra-core-val:
  stage: val
  rules:
  - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "env/val"'
    when: on_success
    changes:
      - demos/v1-self-managed/time-keeper-gcp/**/* 
  script: echo "Running VALIDATION Environment for Core Infra!"

v1-infra-core-pp:
  stage: pp
  when: manual
  rules:
  - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "env/pp"'
    when: on_success
    changes:
      - demos/v1-self-managed/time-keeper-gcp/**/* 
  script: echo "Running PRE-PRODUCTION Environment for Core Infra!"

v1-infra-core-p:
  stage: p
  when: manual
  rules:
  - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "env/p"'
    when: on_success
    changes:
      - demos/v1-self-managed/time-keeper-gcp/**/* 
  script: echo "Running PRODUCTION Environment for Core Infra!"
