include:
  - local: '/demos/v1-self-managed/v1-ci.yml'
  - local: '/demos/v2-self-managed-multi-region/v2-ci.yml'
stages:
  - automated-testing
  - integration
  - validation
  - pre-production
  - production
