---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-pasta
  namespace: app-pasta
  labels:
    project: google
    app: pasta
    cost-center: google-0001
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pasta
  template:
    metadata:
      labels:
        app: pasta
    spec:
      containers:
      - name: app-pasta
        image: gcr.io/google-samples/node-hello:1.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app-pasta
  namespace: app-pasta
  labels:
    project: google
    app: pasta
    cost-center: google-0001
spec: 
  selector: 
    app: pasta
  ports: 
  - name: http
    port: 80
    protocol: TCP

