---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-helloworld
  namespace: app-helloworld
  labels:
    project: google
    app: helloworld
    cost-center: google-0001
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: app-helloworld
        image: gcr.io/cloudrun/hello
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-helloworld
  namespace: app-helloworld
  labels:
    project: google
    app: helloworld
    cost-center: google-0001
spec: 
  selector: 
    app: helloworld
  ports: 
  - name: http
    port: 8080
    protocol: TCP
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: app-helloworld
  namespace: app-helloworld
spec: 
  gateways:
  - istio-system/ingress-gateway
  hosts: 
  - v2.time-keeper.watch
  http:
  - match:
    - uri:
        prefix: /hello
    route: 
    - destination: 
        host: app-helloworld.app-helloworld.svc.cluster.local
        port: 
          number: 8080

