---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend
  namespace: app-bank-of-anthos
spec: 
  gateways:
  - istio-system/ingress-gateway
  hosts: 
  - "*"
  http:
  - match:
    - uri:
        prefix: /bank
    route: 
    - destination: 
        host: frontend
        port: 
          number: 80